version: '3.7'

services:
  db:
    container_name: "dvidendradar-db"
    build:
      context: .
      dockerfile: Dockerfile.db-local
    command: --replSet replicaset --keyFile /data/keyfile.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-dividendradar}
      MONGO_NON_ROOT_USERNAME: ${MONGO_NON_ROOT_USERNAME:-user}
      MONGO_NON_ROOT_PASSWORD: ${MONGO_NON_ROOT_PASSWORD:-password}
    ports:
      - "27017:27017"
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 15s
